//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jjs.Models
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    public partial class ArticleContent
    {
    	/// <summary>  
        /// 自增长id  
        /// </summary> 
    	[DisplayName("自增长id")]
        public int Id { get; set; }
    	/// <summary>  
        /// 门面图  
        /// </summary> 
    	[DisplayName("门面图")]
        public string ACPhoto { get; set; }
    	/// <summary>  
        /// 标题  
        /// </summary> 
    	[DisplayName("标题")]
        public string ACTitle { get; set; }
    	/// <summary>  
        /// 序列号  
        /// </summary> 
    	[DisplayName("序列号")]
        public Nullable<int> ACSortNum { get; set; }
    	/// <summary>  
        /// 所属设计师id  
        /// </summary> 
    	[DisplayName("所属设计师id")]
        public Nullable<int> DId { get; set; }
    	/// <summary>  
        /// 文章内容  
        /// </summary> 
    	[DisplayName("文章内容")]
        public string AContent { get; set; }
    	/// <summary>  
        /// 文章缩影  
        /// </summary> 
    	[DisplayName("文章缩影")]
        public string ACEpitome { get; set; }
    	/// <summary>  
        /// 链接地址  
        /// </summary> 
    	[DisplayName("链接地址")]
        public string ACLink { get; set; }
    	/// <summary>  
        /// 类型：知识园地/最新动态/团装小区/热播套餐/经典案例/滚动图  
        /// </summary> 
    	[DisplayName("类型：知识园地/最新动态/团装小区/热播套餐/经典案例/滚动图")]
        public string ACType { get; set; }
    	/// <summary>  
        /// 添加时间  
        /// </summary> 
    	[DisplayName("添加时间")]
        public System.DateTime InDateTime { get; set; }
    	/// <summary>  
        /// 修改时间  
        /// </summary> 
    	[DisplayName("修改时间")]
        public System.DateTime EditDateTime { get; set; }
    	/// <summary>  
        /// 添加人  
        /// </summary> 
    	[DisplayName("添加人")]
        public string InUserName { get; set; }
    	/// <summary>  
        /// 修改人  
        /// </summary> 
    	[DisplayName("修改人")]
        public string EditUserName { get; set; }
    }
}
