//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jjs.Models
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    public partial class Designer
    {
    	/// <summary>  
        /// 自增长id  
        /// </summary> 
    	[DisplayName("自增长id")]
        public int Id { get; set; }
    	/// <summary>  
        /// 设计师名字  
        /// </summary> 
    	[DisplayName("设计师名字")]
        public string DName { get; set; }
    	/// <summary>  
        /// 设计师图片  
        /// </summary> 
    	[DisplayName("设计师图片")]
        public string DPhoto { get; set; }
    	/// <summary>  
        /// 毕业院校  
        /// </summary> 
    	[DisplayName("毕业院校")]
        public string DUniversity { get; set; }
    	/// <summary>  
        /// 设计理念  
        /// </summary> 
    	[DisplayName("设计理念")]
        public string DIdea { get; set; }
    	/// <summary>  
        /// 所在部门  
        /// </summary> 
    	[DisplayName("所在部门")]
        public string DDepartment { get; set; }
    	/// <summary>  
        /// 扩展字段  
        /// </summary> 
    	[DisplayName("扩展字段")]
        public string DExtend { get; set; }
    	/// <summary>  
        /// 序列号  
        /// </summary> 
    	[DisplayName("序列号")]
        public int DSortNum { get; set; }
    	/// <summary>  
        /// 添加时间  
        /// </summary> 
    	[DisplayName("添加时间")]
        public Nullable<System.DateTime> InDateTime { get; set; }
    	/// <summary>  
        /// 修改时间  
        /// </summary> 
    	[DisplayName("修改时间")]
        public Nullable<System.DateTime> EditDateTime { get; set; }
    	/// <summary>  
        /// 添加人  
        /// </summary> 
    	[DisplayName("添加人")]
        public string InUserName { get; set; }
    	/// <summary>  
        /// 修改人  
        /// </summary> 
    	[DisplayName("修改人")]
        public string EditUserName { get; set; }
    }
}
