//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jjs.Models
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    public partial class Message
    {
    	/// <summary>  
        /// 自增长id  
        /// </summary> 
    	[DisplayName("自增长id")]
        public int Id { get; set; }
    	/// <summary>  
        /// 名字  
        /// </summary> 
    	[DisplayName("名字")]
        public string Name { get; set; }
    	/// <summary>  
        /// 电话  
        /// </summary> 
    	[DisplayName("电话")]
        public string Phone { get; set; }
    	/// <summary>  
        /// 地址  
        /// </summary> 
    	[DisplayName("地址")]
        public string Address { get; set; }
    	/// <summary>  
        /// 扩展字段  
        /// </summary> 
    	[DisplayName("扩展字段")]
        public string Extend { get; set; }
    	/// <summary>  
        /// 添加时间  
        /// </summary> 
    	[DisplayName("添加时间")]
        public Nullable<System.DateTime> InDateTime { get; set; }
    	/// <summary>  
        /// 修改时间  
        /// </summary> 
    	[DisplayName("修改时间")]
        public Nullable<System.DateTime> EditDateTime { get; set; }
    	/// <summary>  
        /// 添加人  
        /// </summary> 
    	[DisplayName("添加人")]
        public string InUserName { get; set; }
    	/// <summary>  
        /// 修改人  
        /// </summary> 
    	[DisplayName("修改人")]
        public string EditUserName { get; set; }
    }
}
